name: Manual Matrix Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: linux
            runner: '["runs-on=${{ github.run_id }}", "runner=4cpu-linux-x64"]'
          - os: windows
            runner: windows-latest
          - os: macos
            runner: macos-latest

    runs-on: ${{ fromJson(matrix.runner) }}

    steps:
      - name: Say pass
        run: echo "pass ✅"
