name: Manual Matrix Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: linux
            runner: '[ "runs-on=${{ github.run_id }}", "runner=4cpu-linux-x64" ]'
          - os: windows
            runner: '["windows-latest"]'
          - os: macos
            runner: '["macos-latest"]'

    runs-on: ${{ fromJson(matrix.runner) }}
    steps:
      - name: Say pass
        run: echo "pass ✅"

  test2:
    strategy:
      matrix:
        os2: [windows-latest, "runs-on=${{ github.run_id }}/runner=4cpu-linux-x64"]
    runs-on: ${{ matrix.os2 }}
    steps:
      - name: Say pass2
        run: echo "pass2 ✅"
